//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson10.WorkingWithSP.ViaEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyExampleEntities : DbContext
    {
        public MyExampleEntities()
            : base("name=MyExampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Products> Products { get; set; }
    
        public virtual ObjectResult<GetProducts_Result> GetProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProducts_Result>("GetProducts");
        }
    
        public virtual ObjectResult<GetProductsFilteredByRating_Result> GetProductsFilteredByRating(Nullable<int> rating)
        {
            var ratingParameter = rating.HasValue ?
                new ObjectParameter("rating", rating) :
                new ObjectParameter("rating", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsFilteredByRating_Result>("GetProductsFilteredByRating", ratingParameter);
        }
    
        public virtual ObjectResult<GetProductsById_Result> GetProductsById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsById_Result>("GetProductsById", idParameter);
        }
    
        public virtual ObjectResult<GetTwoCollectionOfProducts_Result> GetTwoCollectionOfProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTwoCollectionOfProducts_Result>("GetTwoCollectionOfProducts");
        }
    }
}
